name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**.swift"
      - "**.yml"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

env:
  LOG_LEVEL: info
  SWIFT_DETERMINISTIC_HASHING: 1

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build with warnings as errors
        # Pass the flags through an environment variable to avoid conflicts
        env:
          SWIFT_BUILD_FLAGS: "-Xswiftc -warnings-as-errors -Xcc -Werror"
        run: |
          swift build --build-tests --configuration debug $SWIFT_BUILD_FLAGS
      - name: Run Tests
        run: swift test --skip-build --configuration debug --disable-xctest
